### ISSUE TITLE
Failed to execute script deid-chrome

### ISSUE THREAD

**Issue by chalbiophysics** [pearcetm/svs-deidentifier#14]
Hello,

Thank you for your great work !
I downloaded svs-deidentifier-windows-chrome-onefile.zip, unzipped it and ran it.
Two boxes opened : 
- A chrome box : "Error : 404 Not found" 
- A box Fatal error detected : "Failed to execute script deid-chrome"
My computer is a Windows 64
I am using Python 3.7
All packages have been installed like described here : https://github.com/pearcetm/svs-deidentifier/blob/master/wsideidentifier.py
Both chrome and Edge are installed.
I have the feeling that I am missing something, but I do not know what...
Please, could you let me know if you have any idea about the way to solve this issue ?

Kindly yours.

**Comment by pearcetm** [comment]
I haven't see an error like you're describing before - but I also haven't tested on a lot of different Windows operating systems. When you say "Windows 64" which OS are you actually using?

A couple of questions and things to try:  
1) Does "one-dir" mode work?  
2) If you launch from the command line are there any other error messages that give information about where the problem is?
3) If you build the project on your computer, does that work? You can try in either one-file or one-dir mode.
4) Have you tried it on other operating systems and/or computers?
5) Eel uses port 8000 by default. Is another local server already running on that port? Is that port allowed by your firewall/security settings?

**Comment by chalbiophysics** [comment]
Dear @pearcetm thank you for your answer
When you say "Windows 64" which OS are you actually using? => Windows 10 family 64x

    Does "one-dir" mode work? => **Indeed it worked !**
    If you launch from the command line are there any other error messages that give information about where the problem is? => apparently it was a problem of Eel. I I had module not found error although it was actually installed...
    If you build the project on your computer, does that work? You can try in either one-file or one-dir mode. No, still eel module error
    Have you tried it on other operating systems and/or computers? No, but I should definitely try
    Eel uses port 8000 by default. Is another local server already running on that port? Is that port allowed by your firewall/security settings? I guess not

By the way, thank you very much for your help !

Kindly !
